---

- name: "Update default file"
  hosts: localhost
  tasks:
    - name: Create pxelinux.cfg directory
      file:
        path: /tftpboot/pxelinux.cfg
        state: directory
    - name: Create default file in pxelinux.cfg
      copy:
        dest: "/tftpboot/pxelinux.cfg/default"
        content: |
          DEFAULT menu.c32
          PROMPT 0
          MENU TITLE ########## PXE Boot Menu ##########
          TIMEOUT 150
          TOTALTIMEOUT 6000
          ONTIMEOUT 1  # go to this label after timeout expires
          
          LABEL 1
          MENU LABEL ^1) Install CentOS 7 x64 over the network with Kickstart
          KERNEL centos7/vmlinuz
          # CHANGE THE FTP ADDRESS ON THE NEXT LINE (e.g. ftp://ftp:ftp@<mgmt_node_ip>/pub/anaconda-ks.cfg)
          APPEND initrd=centos7/initrd.img inst.ks=ftp://ftp:ftp@{{mgmt_ip}}.1/pub/anaconda-ks.cfg inst.cmdline inst.gpt console=ttyS1,115200n8
          
          LABEL local
          MENU LABEL ^2) local boot
          MENU DEFAULT
          COM32 chain.c32
          APPEND hd0

