---
- name: setup syslinux for PXE network boot server
  hosts: localhost
  tasks:
    - name: copy contents of syslinux to /tftpboot
      copy:
        src: /usr/share/syslinux/
        dest: /tftpboot

