---

- name: "Firewall actions"
  hosts: management
  gather_facts: no
  tasks:

    - name: "Stop and disable firewalld"
      service:
        name: firewalld
        state: stopped
        enabled: no

