
- name: install packages exclusive to management node
  gather_facts: no
  hosts: all
  tasks:
  - name: "Install packages exclusive to management node"
    dnf:
       name:
         - iptables-services
         - epel-release
         - make
         - tar
         - gcc
         - readline-devel
         - libibverbs-utils 
         - infiniband-diags 
         - perftest 
         - libmlx4 
         - libibverbs 
         - opensm
         - net-tools
         - openmpi
         - openmpi-devel
       state: latest

- name: "dnf config manager"
  gather_facts: no
  hosts: management, compute
  tasks:
  - name: enable powertools
    ansible.builtin.shell:
      cmd: "dnf config-manager --set-enabled powertools"

- name: "install epel on all nodes"
  gather_facts: no
  hosts: management, compute
  tasks:
  - name: Install epel on all nodes
    dnf:
       name:
         - epel-release

- name: "install packages on all nodes"
  gather_facts: no
  hosts: management, compute
  tasks:
  - name: Install packages on all nodes
    dnf:
       name:
         - wget 
         - rpm-build 
         - bzip2-devel 
         - perl-ExtUtils-MakeMaker 
         - openssl 
         - openssl-devel 
         - pam-devel 
         - readline-devel 
         - mariadb-server 
         - mariadb-devel 
         - python3 
         - libtool 
         - munge
         - perl-Switch
         - munge-devel
         - nfs-utils 
         - libnfs-utils
         - mpitests-openmpi
         - chrony
         - atlas-devel
       state: latest
