---

# NOTE: Assume /etc/hosts has already been generated on the mgmt node

- name: copying hosts and resolv.conf to compute nodes 
  hosts: all
  gather_facts: no
  tasks:
  - name: copy /etc/hosts to compute nodes
    copy:
      src: /etc/hosts
      dest: /etc/hosts
  - name: copy /etc/resolv.conf to compute nodes
    copy:
      src: /etc/resolv.conf
      dest: /etc/resolv.conf
    
...
